# Generated by Django 5.0.7 on 2024-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('server', models.CharField(max_length=128)),
                ('port', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_from', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=64, null=True)),
                ('date_sent', models.DateTimeField()),
                ('date_received', models.DateTimeField()),
                ('body', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(to='emails.file')),
            ],
        ),
    ]
